name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Clean build
      run: make clean

    - name: Build retransmitter
      run: make retransmitter

